### ISSUE TITLE
Map needs a pan tool

### ISSUE THREAD

**Issue by riknoll** [riknoll/pxt-level-editor#17]
The minimap will be used to pan across the grid, but you'll also be able to use this tool to move in smaller increments. The pan tool will be your usual grab the workspace and drag to scroll.

Best thing to do would probably make a camera class that the minimap can also use.

The pan tool should show and open hand when hovering and a grabbing hand when the user is clicking.

**Comment by danimalquackers** [comment]
I'll take a look at this.
